/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.*;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.event.*;

/**
 *
 * @author Pratap Singh Rathore
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Kajal Sharma
    private void initComponents() {
        jLabel1 = new JLabel();
        subb = new JComboBox<>();
        sname = new JTextField();
        sroll = new JTextField();
        jLabel3 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jLabel4 = new JLabel();
        sem = new JTextField();
        jLabel5 = new JLabel();
        suba = new JComboBox<>();
        subc = new JComboBox<>();
        subd = new JComboBox<>();
        sub1 = new JLabel();
        sub2 = new JLabel();
        sub4 = new JLabel();
        sub3 = new JLabel();
        jButton3 = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //---- jLabel1 ----
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel1.setText("Name     :");

        //---- subb ----
        subb.setModel(new DefaultComboBoxModel<>(new String[] {

        }));
        subb.setMinimumSize(new Dimension(30, 20));
        subb.setPreferredSize(new Dimension(30, 20));
        subb.addPopupMenuListener(new PopupMenuListener() {
            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {}
            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                subbPopupMenuWillBecomeInvisible(e);
            }
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {}
        });
        subb.addActionListener(e -> subbActionPerformed(e));

        //---- sname ----
        sname.addActionListener(e -> snameActionPerformed(e));

        //---- sroll ----
        sroll.addActionListener(e -> srollActionPerformed(e));

        //---- jLabel3 ----
        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel3.setText("Roll No.   :");

        //---- jButton1 ----
        jButton1.setFont(new Font("Times New Roman", Font.BOLD, 14));
        jButton1.setText("OK");
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));

        //---- jButton2 ----
        jButton2.setFont(new Font("Times New Roman", Font.BOLD, 14));
        jButton2.setText("Cancel");
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));

        //---- jLabel4 ----
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 15));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("ADD STUDENT INFO");

        //---- sem ----
        sem.addActionListener(e -> semActionPerformed(e));

        //---- jLabel5 ----
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 13));
        jLabel5.setText("Semester");

        //---- suba ----
        suba.setModel(new DefaultComboBoxModel<>(new String[] {

        }));
        suba.setMinimumSize(new Dimension(30, 20));
        suba.setPreferredSize(new Dimension(30, 20));
        suba.addPopupMenuListener(new PopupMenuListener() {
            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {}
            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                subaPopupMenuWillBecomeInvisible(e);
            }
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {}
        });
        suba.addActionListener(e -> subaActionPerformed(e));

        //---- subc ----
        subc.setModel(new DefaultComboBoxModel<>(new String[] {

        }));
        subc.setMinimumSize(new Dimension(30, 20));
        subc.setPreferredSize(new Dimension(30, 20));
        subc.addPopupMenuListener(new PopupMenuListener() {
            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {}
            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                subcPopupMenuWillBecomeInvisible(e);
            }
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {}
        });
        subc.addActionListener(e -> subcActionPerformed(e));

        //---- subd ----
        subd.setModel(new DefaultComboBoxModel<>(new String[] {

        }));
        subd.setMinimumSize(new Dimension(30, 20));
        subd.setPreferredSize(new Dimension(30, 20));
        subd.addPopupMenuListener(new PopupMenuListener() {
            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {}
            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                subdPopupMenuWillBecomeInvisible(e);
            }
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {}
        });
        subd.addActionListener(e -> subdActionPerformed(e));

        //---- sub1 ----
        sub1.setFont(new Font("Times New Roman", Font.PLAIN, 16));
        sub1.setText("sub 1");

        //---- sub2 ----
        sub2.setFont(new Font("Times New Roman", Font.PLAIN, 16));
        sub2.setText("sub 2");

        //---- sub4 ----
        sub4.setFont(new Font("Times New Roman", Font.PLAIN, 16));
        sub4.setText("sub 4");

        //---- sub3 ----
        sub3.setFont(new Font("Times New Roman", Font.PLAIN, 16));
        sub3.setText("sub 3");

        //---- jButton3 ----
        jButton3.setFont(new Font("Times New Roman", Font.BOLD, 14));
        jButton3.setText("Reset");
        jButton3.addActionListener(e -> jButton3ActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(65, 65, 65)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(sem, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 60, Short.MAX_VALUE))
                        .addComponent(sname)
                        .addComponent(sroll))
                    .addGap(224, 224, 224))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(sub3, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(36, 36, 36))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(132, 132, 132)
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sub4, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(subd, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                    .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12))))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(suba, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sub1, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(subb, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sub2, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                    .addGap(119, 119, 119))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(sname, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addGap(2, 2, 2)))
                    .addGap(16, 16, 16)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(sroll, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(sem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(suba, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                        .addComponent(subb, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(sub1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub2, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(subd, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                        .addComponent(subc, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(sub3, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(sub4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(36, 36, 36)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
                    .addGap(60, 60, 60))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void fillCombo()
    {
        try {
            DbCon dc = new DbCon();
            String stc = "SELECT * FROM subject;";
            ResultSet ft = dc.dql(stc);
            
            while(ft.next())
            {
                suba.addItem(ft.getString(2));
                subb.addItem(ft.getString(2));
                subc.addItem(ft.getString(2));
                subd.addItem(ft.getString(2));
            }
        } catch (Exception e) {
        }
    }
    private void subbPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subbPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_subbPopupMenuWillBecomeInvisible

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void srollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srollActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DbCon ob = new DbCon();
            String name = sname.getText();
            String roll = sroll.getText();
            String sems = sem.getText();
            String s1 = suba.getSelectedItem().toString();
            String s2 = subb.getSelectedItem().toString();
            String s3 = subc.getSelectedItem().toString();
            String s4 = subd.getSelectedItem().toString();
            
            String sql = "insert into students values('"+roll+"','"+name+"','"+sems+"','"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
            int re = ob.dml(sql);
            if(re>0)
            {
                JOptionPane.showMessageDialog(null,"Saved successfully!!!");
            }

        } catch (Exception e ) {
            JOptionPane.showMessageDialog(null,"Error : "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminIndex ob = new AdminIndex();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void subaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:

    }//GEN-LAST:event_subaPopupMenuWillBecomeInvisible

    private void subcPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subcPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_subcPopupMenuWillBecomeInvisible

    private void subdPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_subdPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_subdPopupMenuWillBecomeInvisible

    private void subaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subaActionPerformed
        sub1.setText(suba.getSelectedItem().toString());
    }//GEN-LAST:event_subaActionPerformed

    private void subbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbActionPerformed
        sub2.setText(subb.getSelectedItem().toString());
    }//GEN-LAST:event_subbActionPerformed

    private void subcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcActionPerformed
        sub3.setText(subc.getSelectedItem().toString());
    }//GEN-LAST:event_subcActionPerformed

    private void subdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subdActionPerformed
        sub4.setText(subd.getSelectedItem().toString());
    }//GEN-LAST:event_subdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        sname.setText("");
        sroll.setText("");
        sem.setText("");
        suba.setSelectedIndex(0);
        subb.setSelectedIndex(0);
        subc.setSelectedIndex(0);
        subd.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Kajal Sharma
    private JLabel jLabel1;
    private JComboBox<String> subb;
    private JTextField sname;
    private JTextField sroll;
    private JLabel jLabel3;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel4;
    private JTextField sem;
    private JLabel jLabel5;
    private JComboBox<String> suba;
    private JComboBox<String> subc;
    private JComboBox<String> subd;
    private JLabel sub1;
    private JLabel sub2;
    private JLabel sub4;
    private JLabel sub3;
    private JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
